//! Managed files: the header, the hash, and never clobbering a human's edit
//! (spec §10.4 rules 1 and 2).
//!
//! Every file Unihelm fully owns starts with a line naming the hash of the rest
//! of the file:
//!
//! ```text
//! # UNIHELM-MANAGED sha256:9f2c…  — edited by hand? the panel will tell you.
//! server {
//!     …
//! ```
//!
//! Before a re-render, we read that line back and re-hash the body. If they
//! disagree, somebody edited the file, and the panel stops rather than throwing
//! their work away. That single rule is the difference between a panel a
//! sysadmin can live with and one they end up fighting.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::{ConfigError, Result};

const MARKER: &str = "UNIHELM-MANAGED sha256:";

/// A short reminder in the header, so somebody who opens the file in `vi` knows
/// what they are looking at before they change it.
const NOTICE: &str = "generated by Unihelm — edits are detected, not overwritten";

/// How the target format spells a comment.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CommentStyle {
    /// nginx, systemd, logrotate, shell.
    Hash,
    /// php.ini and PHP-FPM pool files.
    Semicolon,
}

impl CommentStyle {
    pub const fn prefix(self) -> &'static str {
        match self {
            CommentStyle::Hash => "#",
            CommentStyle::Semicolon => ";",
        }
    }
}

/// What we found on disk where a managed file should be.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FileState {
    /// Nothing there yet.
    Absent,
    /// Ours, and untouched since we wrote it.
    Managed { hash: String },
    /// Ours, but the body no longer matches the header — a human edited it.
    Drifted { expected: String, actual: String },
    /// A file exists that we never wrote. Adopting it silently would destroy
    /// somebody's configuration, so this is its own state.
    Foreign,
    /// Present but unreadable (permissions, or not valid UTF-8).
    Unreadable { reason: String },
}

impl FileState {
    /// May the panel write over this without asking?
    pub const fn is_safe_to_overwrite(&self) -> bool {
        matches!(self, FileState::Absent | FileState::Managed { .. })
    }

    pub const fn is_drifted(&self) -> bool {
        matches!(self, FileState::Drifted { .. })
    }
}

/// Hash of a file body, as it appears in the header.
pub fn body_hash(body: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(body.as_bytes());
    hex::encode(hasher.finalize())
}

/// Prepend the managed header to a rendered body.
pub fn with_header(body: &str, style: CommentStyle) -> String {
    let prefix = style.prefix();
    format!(
        "{prefix} {MARKER}{}\n{prefix} {NOTICE}\n{body}",
        body_hash(body)
    )
}

/// Split a managed file into its claimed hash and its body.
///
/// Returns `None` when the file has no header — meaning we did not write it.
pub fn split_header(contents: &str) -> Option<(String, &str)> {
    let (first, rest) = contents.split_once('\n')?;
    let marker_at = first.find(MARKER)?;
    // Everything before the marker must be just a comment prefix and spaces,
    // otherwise this is a coincidence in somebody else's file.
    let lead = &first[..marker_at];
    if !lead
        .trim_end()
        .chars()
        .all(|c| c == '#' || c == ';' || c.is_whitespace())
    {
        return None;
    }

    let hash: String = first[marker_at + MARKER.len()..]
        .trim()
        .chars()
        .take_while(|c| c.is_ascii_hexdigit())
        .collect();
    if hash.len() != 64 {
        return None;
    }

    // The notice line is part of the header, not the body.
    let body = match rest.split_once('\n') {
        Some((notice, after)) if notice.contains(NOTICE) => after,
        _ => rest,
    };
    Some((hash, body))
}

/// Classify what is currently at `path`.
pub fn inspect(path: &Path) -> FileState {
    let contents = match std::fs::read_to_string(path) {
        Ok(c) => c,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return FileState::Absent,
        Err(e) => {
            return FileState::Unreadable {
                reason: e.to_string(),
            };
        }
    };

    let Some((claimed, body)) = split_header(&contents) else {
        return FileState::Foreign;
    };

    let actual = body_hash(body);
    if actual == claimed {
        FileState::Managed { hash: actual }
    } else {
        FileState::Drifted {
            expected: claimed,
            actual,
        }
    }
}

/// Read the body of a managed file, for diffing against a fresh render.
pub fn read_body(path: &Path) -> Result<Option<String>> {
    match std::fs::read_to_string(path) {
        Ok(contents) => Ok(split_header(&contents).map(|(_, body)| body.to_string())),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(ConfigError::Io {
            path: path.to_path_buf(),
            source: e,
        }),
    }
}

/// Write `contents` to `path` atomically.
///
/// The temporary file is created in the same directory so the rename is a true
/// atomic replace — a temp file in `/tmp` would be a copy across filesystems and
/// could leave a half-written config behind.
///
/// # The temporary file carries the same secret the final one does
///
/// It used to be opened with `File::create`, which asks for 0666 and gets 0644
/// under the usual umask, and it was chmodded down only *after* the whole body
/// had been written. For an nginx include that is nothing. For
/// `/etc/unihelm/mail/<domain>.msmtprc` it meant the operator's upstream SMTP
/// password sat in a world-readable file, in a directory every account on the
/// box can traverse, for the length of a write plus an `fsync` — once per site,
/// back to back, every time the relay was saved. Anything that failed after the
/// write left that file there for good, because the only cleanup was on the
/// rename.
///
/// So the mode is settled before any byte of `contents` exists on disk: `.mode()`
/// on the open decides what a newly created file is born as (the umask can only
/// narrow that, never widen it), and the `set_permissions` immediately after
/// pins the exact mode for the two cases the open cannot cover — a umask that
/// took a bit the caller needs, and a leftover temporary file from an older
/// panel that already exists with a mode of its own. Every failure path takes
/// the temporary file with it.
pub fn write_atomic(path: &Path, contents: &str, mode: u32) -> Result<()> {
    let dir = path.parent().ok_or_else(|| ConfigError::BadPath {
        path: path.to_path_buf(),
        reason: "has no parent directory".into(),
    })?;
    std::fs::create_dir_all(dir).map_err(|e| ConfigError::Io {
        path: dir.to_path_buf(),
        source: e,
    })?;

    let file_name = path.file_name().ok_or_else(|| ConfigError::BadPath {
        path: path.to_path_buf(),
        reason: "has no file name".into(),
    })?;
    let mut temp = dir.join(file_name);
    temp.as_mut_os_string().push(".unihelm-tmp");

    if let Err(e) = fill_temp(&temp, contents, mode) {
        let _ = std::fs::remove_file(&temp);
        return Err(e);
    }

    std::fs::rename(&temp, path).map_err(|e| {
        let _ = std::fs::remove_file(&temp);
        ConfigError::Io {
            path: path.to_path_buf(),
            source: e,
        }
    })?;

    // Also sync the directory, so the rename itself survives a crash.
    if let Ok(dir_handle) = std::fs::File::open(dir) {
        let _ = dir_handle.sync_all();
    }
    Ok(())
}

/// Fill the staging file and make it durable.
///
/// Split out so [`write_atomic`] has one place to clean up from: every error in
/// here leaves a file holding some prefix of `contents`, and for a secret a
/// prefix is still a secret.
fn fill_temp(temp: &Path, contents: &str, mode: u32) -> Result<()> {
    use std::io::Write;

    let io = |e: std::io::Error| ConfigError::Io {
        path: temp.to_path_buf(),
        source: e,
    };

    let mut file = create_private(temp, mode)?;
    file.write_all(contents.as_bytes()).map_err(io)?;
    // Durable before the rename: a power cut between write and rename should
    // leave the old config, not an empty new one.
    file.sync_all().map_err(io)
}

/// Open the staging file empty and already at `mode`.
///
/// The whole point of this function is that it returns a handle to a file that
/// is *already* as narrow as the finished config will be, so that no byte of a
/// secret ever exists on disk under a wider one. Two steps, because neither
/// covers the other: `.mode()` decides what a file being created is born as and
/// is ignored for a file that already exists, and the `set_permissions` fixes
/// both the file that already existed — a leftover from a crashed write, or one
/// written by a panel old enough to have created it 0644 — and a umask strict
/// enough to have taken a bit the caller needs. The truncate happens at open, so
/// a leftover's old contents are gone before either.
fn create_private(temp: &Path, mode: u32) -> Result<std::fs::File> {
    use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};

    let io = |e: std::io::Error| ConfigError::Io {
        path: temp.to_path_buf(),
        source: e,
    };

    let file = std::fs::OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .mode(mode)
        .open(temp)
        .map_err(io)?;
    file.set_permissions(std::fs::Permissions::from_mode(mode))
        .map_err(io)?;
    Ok(file)
}

/// Bring an existing file or directory to `mode`, reporting what it was.
///
/// `Ok(None)` means nothing moved — it already matched, or there is nothing
/// there. `Ok(Some(previous))` means it did not match and now does, and the
/// caller is expected to say so somewhere an operator will read.
///
/// This exists because [`crate::ConfigEngine::apply`] short-circuits when the
/// rendered body is byte-identical to what is on disk: no write, and so no
/// chmod. That is the right call for churn and the wrong one for migration — a
/// file a previous version of the panel left at a wide mode keeps that mode for
/// exactly as long as its content does not change, which for a mail relay
/// configuration is forever. Callers that own a secret run this on every pass so
/// a server already in production is fixed by the next apply rather than by a
/// reinstall.
pub fn enforce_mode(path: &Path, mode: u32) -> Result<Option<u32>> {
    use std::os::unix::fs::PermissionsExt;

    let current = match std::fs::metadata(path) {
        // The whole low twelve bits, not just rwx: a setgid bit on a config
        // file is as much a leftover to clear as a group-read bit.
        Ok(meta) => meta.permissions().mode() & 0o7777,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(e) => {
            return Err(ConfigError::Io {
                path: path.to_path_buf(),
                source: e,
            });
        }
    };
    if current == mode {
        return Ok(None);
    }
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(mode)).map_err(|e| {
        ConfigError::Io {
            path: path.to_path_buf(),
            source: e,
        }
    })?;
    Ok(Some(current))
}

/// Remove a managed file, refusing to delete one we did not write.
pub fn remove_managed(path: &Path) -> Result<bool> {
    match inspect(path) {
        FileState::Absent => Ok(false),
        FileState::Foreign => Err(ConfigError::Foreign {
            path: path.to_path_buf(),
        }),
        FileState::Unreadable { reason } => Err(ConfigError::BadPath {
            path: path.to_path_buf(),
            reason,
        }),
        FileState::Managed { .. } | FileState::Drifted { .. } => {
            std::fs::remove_file(path).map_err(|e| ConfigError::Io {
                path: path.to_path_buf(),
                source: e,
            })?;
            Ok(true)
        }
    }
}

/// A unified-ish diff, for the "somebody edited this" screen.
///
/// Not a real diff algorithm: line-by-line is enough to show a sysadmin what
/// they changed, and pulling in a diff crate for one screen is weight the
/// budget does not need.
pub fn simple_diff(current: &str, proposed: &str) -> Vec<DiffLine> {
    let current: Vec<&str> = current.lines().collect();
    let proposed: Vec<&str> = proposed.lines().collect();
    let mut out = Vec::new();

    let mut i = 0;
    while i < current.len() || i < proposed.len() {
        match (current.get(i), proposed.get(i)) {
            (Some(a), Some(b)) if a == b => out.push(DiffLine {
                line: i + 1,
                kind: DiffKind::Same,
                text: (*a).to_string(),
            }),
            (Some(a), Some(b)) => {
                out.push(DiffLine {
                    line: i + 1,
                    kind: DiffKind::Removed,
                    text: (*a).to_string(),
                });
                out.push(DiffLine {
                    line: i + 1,
                    kind: DiffKind::Added,
                    text: (*b).to_string(),
                });
            }
            (Some(a), None) => out.push(DiffLine {
                line: i + 1,
                kind: DiffKind::Removed,
                text: (*a).to_string(),
            }),
            (None, Some(b)) => out.push(DiffLine {
                line: i + 1,
                kind: DiffKind::Added,
                text: (*b).to_string(),
            }),
            (None, None) => break,
        }
        i += 1;
    }
    out
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct DiffLine {
    pub line: usize,
    pub kind: DiffKind,
    pub text: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum DiffKind {
    Same,
    Added,
    Removed,
}

/// The mode a Postfix lookup table is held at, source and compiled copy alike.
///
/// A named constant rather than a literal inside the constructor because
/// [`enforce_map_companion_modes`] has to use the *same* number: a `0600`
/// `sasl_passwd` beside a `0644` `sasl_passwd.db` is a protected file next to
/// an unprotected copy of the same password, and the whole point of naming it
/// once is that the two cannot drift apart.
pub const POSTFIX_MAP_MODE: u32 = 0o600;

/// The mode Postfix's `main.cf` is held at. See [`ManagedFile::postfix_main_cf`]
/// for why this one is world-readable on purpose.
pub const POSTFIX_MAIN_CF_MODE: u32 = 0o644;

/// Hold every compiled copy of a Postfix map at the map's own mode.
///
/// The panel never runs `postmap` — `main.cf` names its maps `texthash:`, so
/// there is no compiled copy to make (see [`crate::paths::POSTFIX_MAP_TYPE`]).
/// This exists for the copies that are there anyway: a machine adopted from an
/// existing Postfix setup, or an operator who followed a relay tutorial and ran
/// `postmap /etc/unihelm/mail/sasl_passwd` by hand. Every one of those files
/// holds the same relay password as its source, with permissions of its own —
/// `postmap` creates the output with the *source's* mode on modern Postfix, but
/// a file created by an older one, or by a `postmap` run under a loose umask,
/// keeps whatever it was born with, and it is the copy nobody thinks to check.
///
/// Returns the files it actually moved and the mode each one had, so a caller
/// can say so somewhere an operator will read; a companion that is absent, or
/// already correct, is not reported. Ignoring the return value is fine — the
/// tightening has already happened.
pub fn enforce_map_companion_modes(map: &Path, mode: u32) -> Result<Vec<(PathBuf, u32)>> {
    let mut moved = Vec::new();
    for companion in crate::paths::postfix_map_companions(map) {
        if let Some(previous) = enforce_mode(&companion, mode)? {
            moved.push((companion, previous));
        }
    }
    Ok(moved)
}

/// A file the panel owns, and where it lives.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ManagedFile {
    pub path: PathBuf,
    pub mode: u32,
    pub comment_style: CommentStyle,
}

impl ManagedFile {
    /// An nginx include, 0644 so nginx (running as its own user) can read it.
    pub fn nginx(path: impl Into<PathBuf>) -> Self {
        Self {
            path: path.into(),
            mode: 0o644,
            comment_style: CommentStyle::Hash,
        }
    }

    /// An Apache vhost. Same shape as [`ManagedFile::nginx`] — 0644 so Apache,
    /// running as its own user, can read it, and `#` comments.
    pub fn apache(path: impl Into<PathBuf>) -> Self {
        Self {
            path: path.into(),
            mode: 0o644,
            comment_style: CommentStyle::Hash,
        }
    }

    /// A PHP-FPM pool file. Comments are semicolons, and 0640 because the only
    /// reader is the FPM master, which opens it as root before dropping to the
    /// pool's own user — so nothing is lost by closing it to everyone else.
    ///
    /// It was 0644, which put one tenant's isolation settings in front of every
    /// other tenant on the box: their Linux user and group, their socket path,
    /// their `open_basedir`, and the exact list of functions they may still
    /// call. Anyone who got a shell as any tenant could read the whole map of
    /// their neighbours before deciding where to push. Containerised FPM is
    /// unaffected: `unihelm_ops::fpmcontainer` bind-mounts this directory
    /// read-only and starts the master with no `--user`, so it is root there too.
    pub fn fpm_pool(path: impl Into<PathBuf>) -> Self {
        Self {
            path: path.into(),
            mode: 0o640,
            comment_style: CommentStyle::Semicolon,
        }
    }

    /// A MariaDB drop-in. Read by `mariadbd` as root before it drops to the
    /// `mysql` user, and hash-commented like the rest of the my.cnf family.
    pub fn mysql(path: impl Into<PathBuf>) -> Self {
        Self {
            path: path.into(),
            mode: 0o644,
            comment_style: CommentStyle::Hash,
        }
    }

    /// One site's outbound mail relay configuration (`unihelm_ops::mail`).
    ///
    /// 0640, and the caller gives it to `root:<that site's tenant group>`. Both
    /// halves are load-bearing and neither is optional:
    ///
    /// - group-readable because msmtp runs as the tenant — PHP's `mail()` does —
    ///   so the account that has to send is the account that has to read it;
    /// - root-*owned* because an owner may chmod their own file and then write
    ///   to it, and a tenant who could edit this could point their site's mail
    ///   at a relay of their own while still sending as the operator's domain.
    ///
    /// 0640 is therefore the narrowest mode that still sends. It is not
    /// isolation and must not be described as any: the relay is one server-wide
    /// credential, so every one of these files holds the *same* secret, and the
    /// mode buys "a tenant cannot read another site's copy", not "a tenant
    /// cannot read the operator's relay password". See `unihelm_ops::mail`.
    pub fn mail_relay(path: impl Into<PathBuf>) -> Self {
        Self {
            path: path.into(),
            mode: 0o640,
            comment_style: CommentStyle::Hash,
        }
    }

    /// Postfix's `main.cf` — the null client's whole configuration.
    ///
    /// `0644`, and unlike every other mode in this file that is not a choice.
    /// Postfix is not one process: `master` starts a dozen daemons which each
    /// re-read `main.cf` *after* dropping to the unprivileged `postfix` user,
    /// and `postconf`, which an operator and the panel's own preflight run as
    /// anybody, reads it too. A narrower mode does not hide anything worth
    /// hiding — the file names the relay host and the *path* of the credential,
    /// never the credential — and it does stop the MTA starting.
    ///
    /// The one file the panel writes outside a directory of its own: `main.cf`
    /// has no `include` and no drop-in directory, so there is no single line to
    /// add. See [`crate::paths::postfix_dir`].
    pub fn postfix_main_cf(path: impl Into<PathBuf>) -> Self {
        Self {
            path: path.into(),
            mode: POSTFIX_MAIN_CF_MODE,
            comment_style: CommentStyle::Hash,
        }
    }

    /// A Postfix lookup table: the relay credential, or the sender-rewriting
    /// map (`unihelm_ops::mail`).
    ///
    /// [`POSTFIX_MAP_MODE`] — `0600`, root-owned, and **this is the whole
    /// difference between this design and the one it replaces**. The msmtp
    /// files these supersede were `0640 root:<tenant>` because msmtp ran as the
    /// tenant, so the account that had to send was the account that had to read
    /// the relay password; one relay for the server meant every tenant held the
    /// credential the operator sends with, and a single customer reading their
    /// own copy could get the machine blacklisted for everyone. Postfix's
    /// `smtp(8)` opens this map in its pre-jail initialisation, while it is
    /// still root, and only then drops to the `postfix` user — so no account
    /// but root ever needs to read it, and none is given the chance.
    ///
    /// Both maps get the same mode. The credential is obvious; the sender map
    /// is every domain hosted on the machine in one file, which is the customer
    /// list, and nothing but Postfix reads that either.
    pub fn postfix_map(path: impl Into<PathBuf>) -> Self {
        Self {
            path: path.into(),
            mode: POSTFIX_MAP_MODE,
            comment_style: CommentStyle::Hash,
        }
    }

    pub fn state(&self) -> FileState {
        inspect(&self.path)
    }

    /// Hold the file at its declared mode, reporting the mode it had if it was
    /// wrong. See [`enforce_mode`] for why an apply that writes nothing still
    /// has to do this.
    pub fn enforce_mode(&self) -> Result<Option<u32>> {
        enforce_mode(&self.path, self.mode)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_freshly_written_file_reads_back_as_managed() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("site.conf");
        let body = "server {\n    listen 443 ssl;\n}\n";

        write_atomic(&path, &with_header(body, CommentStyle::Hash), 0o644).unwrap();

        match inspect(&path) {
            FileState::Managed { hash } => assert_eq!(hash, body_hash(body)),
            other => panic!("expected Managed, got {other:?}"),
        }
        assert_eq!(read_body(&path).unwrap().as_deref(), Some(body));
    }

    #[test]
    fn a_human_edit_is_detected_rather_than_overwritten() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("site.conf");
        write_atomic(
            &path,
            &with_header("server {\n}\n", CommentStyle::Hash),
            0o644,
        )
        .unwrap();

        // Somebody adds a line by hand and does not touch the header.
        let contents = std::fs::read_to_string(&path).unwrap();
        std::fs::write(&path, format!("{contents}# added by a sysadmin at 3am\n")).unwrap();

        let state = inspect(&path);
        assert!(state.is_drifted(), "expected drift, got {state:?}");
        assert!(
            !state.is_safe_to_overwrite(),
            "a drifted file must never be silently replaced"
        );
    }

    #[test]
    fn a_file_we_never_wrote_is_foreign_not_ours() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("site.conf");
        std::fs::write(&path, "server {\n    # hand-written years ago\n}\n").unwrap();

        assert_eq!(inspect(&path), FileState::Foreign);
        assert!(!inspect(&path).is_safe_to_overwrite());
        assert!(matches!(
            remove_managed(&path),
            Err(ConfigError::Foreign { .. })
        ));
        assert!(
            path.exists(),
            "a foreign file must survive a failed removal"
        );
    }

    #[test]
    fn a_forged_header_does_not_make_a_foreign_file_ours() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("site.conf");
        // The marker appears, but inside a directive rather than as a comment.
        std::fs::write(
            &path,
            "server_name UNIHELM-MANAGED sha256:0000;\nserver {}\n",
        )
        .unwrap();
        assert_eq!(inspect(&path), FileState::Foreign);
    }

    #[test]
    fn a_truncated_or_bogus_hash_is_not_trusted() {
        let dir = tempfile::tempdir().unwrap();
        for (name, header) in [
            ("short.conf", "# UNIHELM-MANAGED sha256:abc\n"),
            ("empty.conf", "# UNIHELM-MANAGED sha256:\n"),
            ("nonhex.conf", "# UNIHELM-MANAGED sha256:zzzz\n"),
        ] {
            let path = dir.path().join(name);
            std::fs::write(&path, format!("{header}server {{}}\n")).unwrap();
            assert_eq!(inspect(&path), FileState::Foreign, "{name}");
        }
    }

    #[test]
    fn semicolon_comment_style_works_for_fpm_pools() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("pool.conf");
        let body = "[site]\nuser = uh_abc\n";
        write_atomic(&path, &with_header(body, CommentStyle::Semicolon), 0o644).unwrap();

        let raw = std::fs::read_to_string(&path).unwrap();
        assert!(raw.starts_with("; UNIHELM-MANAGED"), "got: {raw}");
        assert!(matches!(inspect(&path), FileState::Managed { .. }));
        assert_eq!(read_body(&path).unwrap().as_deref(), Some(body));
    }

    #[test]
    fn a_pool_file_is_not_readable_by_the_tenants_it_describes() {
        use std::os::unix::fs::PermissionsExt;

        // At 0644 every tenant on the box could read every other tenant's pool:
        // their Linux user, their socket, their open_basedir and the exact list
        // of functions still available to them. Only the FPM master reads this
        // file, and it does so as root.
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("unihelm-example_com.conf");
        let pool = ManagedFile::fpm_pool(&path);
        assert_eq!(pool.mode, 0o640);

        write_atomic(&path, &with_header("[x]\n", pool.comment_style), pool.mode).unwrap();
        let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
        assert_eq!(
            mode & 0o007,
            0,
            "world can still read a pool file: {mode:o}"
        );

        // The web servers genuinely run as their own user and must keep reading
        // their own files, so this tightening is not theirs to inherit.
        assert_eq!(ManagedFile::nginx("/etc/nginx/x.conf").mode, 0o644);
        assert_eq!(ManagedFile::apache("/etc/apache2/x.conf").mode, 0o644);
    }

    #[test]
    fn atomic_write_leaves_no_temporary_files_behind() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("site.conf");
        write_atomic(&path, "hello\n", 0o644).unwrap();
        write_atomic(&path, "hello again\n", 0o644).unwrap();

        let leftovers: Vec<_> = std::fs::read_dir(dir.path())
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .filter(|n| n.contains("unihelm-tmp"))
            .collect();
        assert!(leftovers.is_empty(), "left behind: {leftovers:?}");
    }

    #[test]
    fn atomic_write_sets_the_requested_mode() {
        use std::os::unix::fs::PermissionsExt;
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("secret.conf");
        write_atomic(&path, "key\n", 0o600).unwrap();
        let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode, 0o600);
    }

    #[test]
    fn the_staging_file_is_narrow_before_the_secret_goes_into_it() {
        use std::os::unix::fs::PermissionsExt;

        // `File::create` asks for 0666 and gets 0644 under the usual umask, and
        // the old order chmodded down only after the body had been written — so
        // the mail relay's password was readable by every account on the box for
        // the length of a write and an fsync. The window is not observable from
        // a test; the property that removes it is, which is that the file is
        // already at its final mode while it is still empty.
        let dir = tempfile::tempdir().unwrap();
        let temp = dir.path().join("relay.msmtprc.unihelm-tmp");
        let handle = create_private(&temp, 0o640).unwrap();

        let mode = std::fs::metadata(&temp).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode, 0o640, "staging file mode: {mode:o}");
        assert_eq!(mode & 0o007, 0, "world can read the staging file: {mode:o}");
        assert_eq!(
            std::fs::read_to_string(&temp).unwrap(),
            "",
            "the mode has to be settled while there is still nothing to read"
        );
        drop(handle);
    }

    #[test]
    fn a_leftover_staging_file_is_narrowed_before_it_is_refilled() {
        use std::os::unix::fs::PermissionsExt;

        // A crash mid-write leaves one of these behind, and one written by a
        // panel old enough to create it 0644 leaves it wide. `.mode()` on the
        // open applies only to a file being *created*, so this is the case the
        // chmod covers: the next secret must not be poured into whatever mode
        // the leftover happened to have.
        let dir = tempfile::tempdir().unwrap();
        let temp = dir.path().join("relay.msmtprc.unihelm-tmp");
        std::fs::write(&temp, "stale\n").unwrap();
        std::fs::set_permissions(&temp, std::fs::Permissions::from_mode(0o666)).unwrap();

        let handle = create_private(&temp, 0o640).unwrap();

        let mode = std::fs::metadata(&temp).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode, 0o640, "leftover mode survived: {mode:o}");
        assert_eq!(
            std::fs::read_to_string(&temp).unwrap(),
            "",
            "the leftover's contents outlived the open"
        );
        drop(handle);
    }

    #[test]
    fn a_failed_write_leaves_no_readable_copy_of_the_secret_behind() {
        // Renaming over a non-empty directory is ENOTEMPTY on every unix, which
        // is the one failure a test can force from outside. The invariant it
        // locks is the general one: no exit from `write_atomic` leaves a file
        // holding some or all of `contents`, because for a relay config even a
        // prefix of it is the operator's password.
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("relay.msmtprc");
        std::fs::create_dir(&path).unwrap();
        std::fs::write(path.join("occupied"), "x").unwrap();

        let err = write_atomic(&path, "password hunter2\n", 0o640).unwrap_err();
        assert!(matches!(err, ConfigError::Io { .. }), "got {err:?}");

        let temp = dir.path().join("relay.msmtprc.unihelm-tmp");
        assert!(
            !temp.exists(),
            "a failed write left the credential at {temp:?}"
        );
    }

    #[test]
    fn enforcing_a_mode_reports_only_the_files_it_actually_moved() {
        use std::os::unix::fs::PermissionsExt;

        // An apply whose rendered body is unchanged writes nothing and therefore
        // chmods nothing, so a server already running keeps whatever mode its
        // relay config was created with. This is the step that fixes it on the
        // next pass, and it has to stay quiet when there is nothing to say —
        // otherwise every apply logs a tightening that did not happen.
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("relay.msmtprc");
        std::fs::write(&path, "password hunter2\n").unwrap();
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o644)).unwrap();

        assert_eq!(enforce_mode(&path, 0o640).unwrap(), Some(0o644));
        let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode, 0o640);

        assert_eq!(enforce_mode(&path, 0o640).unwrap(), None);
        assert_eq!(
            enforce_mode(&dir.path().join("never-written"), 0o640).unwrap(),
            None,
            "a file that is not there is not a file to tighten"
        );
    }

    #[test]
    fn a_relay_config_is_readable_by_the_account_that_sends_and_nobody_else() {
        // msmtp runs as the tenant, so the group bit has to stay; every other
        // account on the box has no business with the operator's relay password.
        let relay = ManagedFile::mail_relay("/etc/unihelm/mail/example.com.msmtprc");
        assert_eq!(relay.mode, 0o640);
        assert_eq!(relay.mode & 0o007, 0, "world-readable relay credential");
        assert_eq!(relay.comment_style, CommentStyle::Hash);
    }

    #[test]
    fn a_postfix_map_is_readable_by_root_and_by_nothing_else() {
        use std::os::unix::fs::PermissionsExt;

        // The msmtp design this replaces had to be group-readable: msmtp ran as
        // the tenant, so the tenant held the operator's relay password. Postfix
        // opens this map as root before it drops privileges, so the group bit
        // buys nothing and costs the entire security argument for the change.
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("sasl_passwd");
        let map = ManagedFile::postfix_map(&path);
        assert_eq!(map.mode, 0o600);
        assert_eq!(
            map.mode & 0o077,
            0,
            "group or world can read: {:o}",
            map.mode
        );
        assert_eq!(map.comment_style, CommentStyle::Hash);

        // The file it replaces, kept alongside so the contrast is a fact in the
        // test suite rather than a claim in a comment.
        assert_eq!(
            ManagedFile::mail_relay("/etc/unihelm/mail/example.com.msmtprc").mode,
            0o640,
            "the per-site msmtp file was group-readable by design"
        );

        write_atomic(
            &path,
            &with_header("relay user:pw\n", map.comment_style),
            map.mode,
        )
        .unwrap();
        let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode, 0o600, "on disk: {mode:o}");
    }

    #[test]
    fn postfix_main_cf_stays_readable_because_every_postfix_daemon_reads_it() {
        // Tempting to lock this down beside the maps, and it would stop the MTA
        // starting: `master` forks a dozen daemons that re-read main.cf after
        // dropping to the unprivileged `postfix` user. It carries the relay
        // host and the *path* of the credential, never the credential.
        let main_cf = ManagedFile::postfix_main_cf("/etc/postfix/main.cf");
        assert_eq!(main_cf.mode, 0o644);
        assert_eq!(main_cf.mode & 0o044, 0o044, "postfix could not read it");
        assert_eq!(main_cf.comment_style, CommentStyle::Hash);
    }

    #[test]
    fn a_compiled_copy_of_a_map_is_held_at_the_same_mode_as_its_source() {
        use std::os::unix::fs::PermissionsExt;

        // `postmap` writes a second file holding the same relay password, and
        // that is the copy people forget: the source gets chmodded because
        // every tutorial says to, the `.db` beside it does not. The panel does
        // not create these — main.cf names its maps `texthash:` — but an
        // adopted machine, or an operator who ran `postmap` by hand, has them.
        let dir = tempfile::tempdir().unwrap();
        let source = dir.path().join("sasl_passwd");
        let map = ManagedFile::postfix_map(&source);
        write_atomic(
            &source,
            &with_header("relay user:pw\n", map.comment_style),
            map.mode,
        )
        .unwrap();

        // One of each extension postmap can produce, all left wide open.
        let companions = crate::paths::postfix_map_companions(&source);
        assert_eq!(companions.len(), 3, "{companions:?}");
        for companion in &companions {
            std::fs::write(companion, "compiled copy of the same password\n").unwrap();
            std::fs::set_permissions(companion, std::fs::Permissions::from_mode(0o644)).unwrap();
        }

        let moved = enforce_map_companion_modes(&source, map.mode).unwrap();
        assert_eq!(moved.len(), 3, "every compiled copy has to be reported");

        for companion in &companions {
            let mode = std::fs::metadata(companion).unwrap().permissions().mode() & 0o777;
            assert_eq!(
                mode,
                map.mode,
                "{} is a readable copy of the relay password: {mode:o}",
                companion.display()
            );
            assert_eq!(mode & 0o077, 0, "{}: {mode:o}", companion.display());
        }

        // Idempotent, and silent when there is nothing to say — an apply that
        // tightens nothing must not log a tightening.
        assert!(
            enforce_map_companion_modes(&source, map.mode)
                .unwrap()
                .is_empty()
        );

        // A map with no compiled copies at all — the normal case — is not an
        // error and reports nothing.
        let untouched = dir.path().join("sender_canonical");
        std::fs::write(&untouched, "uh_abc noreply@example.com\n").unwrap();
        assert!(
            enforce_map_companion_modes(&untouched, POSTFIX_MAP_MODE)
                .unwrap()
                .is_empty()
        );
    }

    // -- the null client's three files ---------------------------------------
    //
    // Rendered here rather than in `templates.rs` because these three are not
    // in the embedded `TEMPLATES` table yet — registering them is orchestrator
    // wiring — and a template nothing renders is a template nothing checks.
    // `add_template` is the supported way to put a source into the environment
    // at runtime, so the checks are the real ones: strict undefined, no
    // escaping, the same trim rules.

    const MAIN_CF: &str = include_str!("../templates/mail/main.cf.j2");
    const SASL_PASSWD: &str = include_str!("../templates/mail/sasl_passwd.j2");
    const SENDER_CANONICAL: &str = include_str!("../templates/mail/sender_canonical.j2");

    fn mail_templates() -> crate::TemplateSet {
        let mut set = crate::TemplateSet::load().expect("the embedded set must load");
        for (name, source) in [
            ("mail/main.cf", MAIN_CF),
            ("mail/sasl_passwd", SASL_PASSWD),
            ("mail/sender_canonical", SENDER_CANONICAL),
        ] {
            set.add_template(name, source)
                .unwrap_or_else(|e| panic!("{name} does not parse: {e:?}"));
        }
        set
    }

    /// A relay the panel would plausibly be pointed at, with the knobs the
    /// tests move named as arguments.
    fn mail_context(tls_mode: &str, username: Option<&str>) -> serde_json::Value {
        serde_json::json!({ "mail": {
            "myhostname": "srv1.hosting.example",
            // One rendered value, used as `relayhost` in main.cf and as the
            // lookup key in sasl_passwd, so the two cannot disagree.
            "relayhost": "[smtp.sendgrid.net]:587",
            "tls_mode": tls_mode,
            "tls_trust_file": "/etc/ssl/certs/ca-certificates.crt",
            "username": username,
            "password": "SG.hunter2",
            "sasl_password_map": "texthash:/etc/unihelm/mail/sasl_passwd",
            "sender_canonical_map": "texthash:/etc/unihelm/mail/sender_canonical",
            "default_sender": "noreply@hosting.example",
            "senders": [{
                "site": "shop.example.com",
                "local_user": "uh_abc123",
                "address": "noreply@shop.example.com",
            }],
        }})
    }

    /// The directives, with the file's own prose stripped. Every one of these
    /// templates explains itself at length, and a comment is not a setting —
    /// which is exactly the distinction Postfix makes too.
    fn directives(rendered: &str) -> String {
        rendered
            .lines()
            .map(str::trim)
            .filter(|l| !l.starts_with('#') && !l.is_empty())
            .collect::<Vec<_>>()
            .join("\n")
    }

    #[test]
    fn the_null_client_delivers_nothing_locally_and_hears_nothing_from_the_network() {
        // The two properties that make this an MTA it is safe to run on every
        // customer-facing box. Losing either turns a mail client into a mail
        // server: `inet_interfaces` into an open SMTP port, `mydestination`
        // into local mailboxes on a machine with no mailbox management at all.
        let rendered = mail_templates()
            .render("mail/main.cf", &mail_context("starttls", Some("apikey")))
            .unwrap();
        let set = directives(&rendered);

        assert!(set.contains("inet_interfaces = loopback-only"), "{set}");
        assert!(
            !set.contains("inet_interfaces = all"),
            "this MTA would accept mail from the internet:\n{set}"
        );
        assert!(
            set.lines().any(|l| l == "mydestination ="),
            "an empty mydestination is what makes it a null client:\n{set}"
        );
        assert!(set.contains("local_transport = error:"), "{set}");
        assert!(set.contains("local_recipient_maps ="), "{set}");

        // Loopback is not "trusted" enough on a shared host: every tenant
        // process can reach 127.0.0.1:25, and without this it could relay to
        // anywhere through the operator's credential — the same exposure this
        // change exists to close, on a different port.
        assert!(
            set.contains("smtpd_relay_restrictions = permit_mynetworks, reject_unauth_destination"),
            "{set}"
        );
    }

    #[test]
    fn the_relay_credential_is_never_offered_over_an_unverified_session() {
        let templates = mail_templates();

        for mode in ["starttls", "implicit"] {
            let rendered = templates
                .render("mail/main.cf", &mail_context(mode, Some("apikey")))
                .unwrap();
            let set = directives(&rendered);

            // `encrypt` requires TLS and verifies nothing — it is satisfied by
            // whoever answers on that address. The msmtp configuration this
            // replaces verified the certificate and the host name, so anything
            // weaker here is a downgrade shipped as an upgrade.
            assert!(
                set.contains("smtp_tls_security_level = secure"),
                "{mode}:\n{set}"
            );
            assert!(
                !set.contains("smtp_tls_security_level = encrypt")
                    && !set.contains("smtp_tls_security_level = may"),
                "{mode} would accept an unverified relay:\n{set}"
            );
            assert!(set.contains("smtp_tls_CAfile = /etc/ssl/certs/"), "{set}");
            assert!(
                set.contains("smtp_tls_mandatory_protocols = >=TLSv1.2"),
                "{set}"
            );
            assert!(set.contains("smtp_sasl_auth_enable = yes"), "{set}");
            // Postfix's default forbids the plaintext mechanisms every
            // submission service actually offers, and leaving it in place
            // produces `no mechanism available` — which reads as a wrong
            // password and costs an afternoon.
            assert!(
                set.contains("smtp_sasl_security_options = noanonymous"),
                "{set}"
            );
        }

        // SMTPS is TLS from the first byte; without wrappermode Postfix speaks
        // plain SMTP into a TLS listener and hangs until the timeout.
        let implicit = templates
            .render("mail/main.cf", &mail_context("implicit", Some("apikey")))
            .unwrap();
        assert!(directives(&implicit).contains("smtp_tls_wrappermode = yes"));
        let starttls = templates
            .render("mail/main.cf", &mail_context("starttls", Some("apikey")))
            .unwrap();
        assert!(!directives(&starttls).contains("smtp_tls_wrappermode = yes"));
    }

    #[test]
    fn a_plaintext_relay_cannot_be_talked_into_sending_the_password_in_the_clear() {
        // The panel refuses to store a password against a plaintext relay, so
        // this combination should not reach the template at all. It renders
        // fail-closed anyway: `noplaintext` means authentication fails rather
        // than the operator's relay password crossing the wire unencrypted.
        let rendered = mail_templates()
            .render("mail/main.cf", &mail_context("none", Some("apikey")))
            .unwrap();
        let set = directives(&rendered);
        assert!(set.contains("smtp_tls_security_level = none"), "{set}");
        assert!(
            set.contains("smtp_sasl_security_options = noanonymous, noplaintext"),
            "a credential could leave this machine in the clear:\n{set}"
        );

        // No credential at all is the ordinary in-datacentre case, and must not
        // render an authentication that cannot happen.
        let anonymous = mail_templates()
            .render("mail/main.cf", &mail_context("starttls", None))
            .unwrap();
        let set = directives(&anonymous);
        assert!(set.contains("smtp_sasl_auth_enable = no"), "{set}");
        assert!(!set.contains("smtp_sasl_password_maps"), "{set}");
    }

    #[test]
    fn the_credential_map_is_keyed_by_the_exact_string_relayhost_uses() {
        // A key that merely looks right — the host without its brackets, or
        // without the port — is not a syntax error. Postfix simply never finds
        // a credential and never attempts authentication, and the relay's
        // rejection reads like a bad password. Both files take the value from
        // one context key so they cannot drift.
        let templates = mail_templates();
        let ctx = mail_context("starttls", Some("apikey"));

        let main_cf = templates.render("mail/main.cf", &ctx).unwrap();
        let map = templates.render("mail/sasl_passwd", &ctx).unwrap();

        assert!(
            directives(&main_cf).contains("relayhost = [smtp.sendgrid.net]:587"),
            "{main_cf}"
        );
        let credential = directives(&map);
        assert_eq!(
            credential, "[smtp.sendgrid.net]:587\tapikey:SG.hunter2",
            "the map key must match relayhost byte for byte"
        );

        // Without a username the table is comments only — a file that exists
        // and holds nothing, rather than a missing map for something to point
        // at later and fail to start on.
        let anonymous = templates
            .render("mail/sasl_passwd", &mail_context("starttls", None))
            .unwrap();
        assert_eq!(directives(&anonymous), "", "{anonymous}");
        assert!(!anonymous.contains("hunter2"), "{anonymous}");
    }

    #[test]
    fn a_relay_context_missing_a_value_fails_to_render_rather_than_sending_as_nothing() {
        // Strict undefined, and it matters more here than in an nginx include:
        // `relayhost = ` is not a syntax error to Postfix, it is a machine that
        // tries to deliver every message itself and queues them all.
        let templates = mail_templates();
        for missing in ["relayhost", "myhostname", "username", "sasl_password_map"] {
            let mut ctx = mail_context("starttls", Some("apikey"));
            ctx["mail"]
                .as_object_mut()
                .expect("the context is an object")
                .remove(missing);
            assert!(
                templates.render("mail/main.cf", &ctx).is_err(),
                "a context with no `{missing}` rendered anyway"
            );
        }
    }

    #[test]
    fn a_site_sends_as_its_own_domain_and_everything_else_as_the_relays_address() {
        // Without this map every message leaves as `uh_abc123@srv1.hosting.
        // example`, which no relay is authorised for: SPF fails and the mail
        // is rejected or filed as spam.
        let rendered = mail_templates()
            .render(
                "mail/sender_canonical",
                &mail_context("starttls", Some("apikey")),
            )
            .unwrap();
        let map = directives(&rendered);

        assert!(
            map.contains("uh_abc123\tnoreply@shop.example.com"),
            "the bare local user is what cron and CLI mail send as:\n{map}"
        );
        assert!(
            map.contains("uh_abc123@srv1.hosting.example\tnoreply@shop.example.com"),
            "the qualified form is what PHP and a local MTA hand over:\n{map}"
        );
        // The catch-all covers root's own mail and any script that set no
        // sender, and must not shadow the per-site entries — Postfix tries
        // `user@domain`, then `user`, then `@domain`, so specificity wins
        // whatever the order in the file.
        assert!(
            map.contains("@srv1.hosting.example\tnoreply@hosting.example"),
            "{map}"
        );
    }

    #[test]
    fn removing_a_managed_file_reports_whether_it_was_there() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("site.conf");
        assert!(
            !remove_managed(&path).unwrap(),
            "absent means nothing was removed"
        );

        write_atomic(&path, &with_header("x\n", CommentStyle::Hash), 0o644).unwrap();
        assert!(remove_managed(&path).unwrap());
        assert!(!path.exists());
    }

    #[test]
    fn a_drifted_file_can_still_be_removed_deliberately() {
        // Deleting a site should not be blocked by an edit to its vhost — the
        // user asked for the site to go away.
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("site.conf");
        write_atomic(&path, &with_header("x\n", CommentStyle::Hash), 0o644).unwrap();
        std::fs::write(
            &path,
            std::fs::read_to_string(&path).unwrap() + "# edited\n",
        )
        .unwrap();
        assert!(inspect(&path).is_drifted());
        assert!(remove_managed(&path).unwrap());
    }

    #[test]
    fn the_header_hash_covers_the_body_only() {
        // Re-rendering identical content must produce an identical file, or
        // every render would look like a change.
        let a = with_header("server {}\n", CommentStyle::Hash);
        let b = with_header("server {}\n", CommentStyle::Hash);
        assert_eq!(a, b);
        assert_ne!(a, with_header("server { }\n", CommentStyle::Hash));
    }

    #[test]
    fn diff_shows_what_changed() {
        let diff = simple_diff("a\nb\nc\n", "a\nB\nc\nd\n");
        let added: Vec<_> = diff
            .iter()
            .filter(|d| d.kind == DiffKind::Added)
            .map(|d| &d.text)
            .collect();
        let removed: Vec<_> = diff
            .iter()
            .filter(|d| d.kind == DiffKind::Removed)
            .map(|d| &d.text)
            .collect();
        assert_eq!(added, vec!["B", "d"]);
        assert_eq!(removed, vec!["b"]);
    }
}
