//! Managed files: the header, the hash, and never clobbering a human's edit
//! (spec §10.4 rules 1 and 2).
//!
//! Every file Unihelm fully owns starts with a line naming the hash of the rest
//! of the file:
//!
//! ```text
//! # UNIHELM-MANAGED sha256:9f2c…  — edited by hand? the panel will tell you.
//! server {
//!     …
//! ```
//!
//! Before a re-render, we read that line back and re-hash the body. If they
//! disagree, somebody edited the file, and the panel stops rather than throwing
//! their work away. That single rule is the difference between a panel a
//! sysadmin can live with and one they end up fighting.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::{ConfigError, Result};

const MARKER: &str = "UNIHELM-MANAGED sha256:";

/// A short reminder in the header, so somebody who opens the file in `vi` knows
/// what they are looking at before they change it.
const NOTICE: &str = "generated by Unihelm — edits are detected, not overwritten";

/// How the target format spells a comment.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CommentStyle {
    /// nginx, systemd, logrotate, shell.
    Hash,
    /// php.ini and PHP-FPM pool files.
    Semicolon,
}

impl CommentStyle {
    pub const fn prefix(self) -> &'static str {
        match self {
            CommentStyle::Hash => "#",
            CommentStyle::Semicolon => ";",
        }
    }
}

/// What we found on disk where a managed file should be.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FileState {
    /// Nothing there yet.
    Absent,
    /// Ours, and untouched since we wrote it.
    Managed { hash: String },
    /// Ours, but the body no longer matches the header — a human edited it.
    Drifted { expected: String, actual: String },
    /// A file exists that we never wrote. Adopting it silently would destroy
    /// somebody's configuration, so this is its own state.
    Foreign,
    /// Present but unreadable (permissions, or not valid UTF-8).
    Unreadable { reason: String },
}

impl FileState {
    /// May the panel write over this without asking?
    pub const fn is_safe_to_overwrite(&self) -> bool {
        matches!(self, FileState::Absent | FileState::Managed { .. })
    }

    pub const fn is_drifted(&self) -> bool {
        matches!(self, FileState::Drifted { .. })
    }
}

/// Hash of a file body, as it appears in the header.
pub fn body_hash(body: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(body.as_bytes());
    hex::encode(hasher.finalize())
}

/// Prepend the managed header to a rendered body.
pub fn with_header(body: &str, style: CommentStyle) -> String {
    let prefix = style.prefix();
    format!(
        "{prefix} {MARKER}{}\n{prefix} {NOTICE}\n{body}",
        body_hash(body)
    )
}

/// Split a managed file into its claimed hash and its body.
///
/// Returns `None` when the file has no header — meaning we did not write it.
pub fn split_header(contents: &str) -> Option<(String, &str)> {
    let (first, rest) = contents.split_once('\n')?;
    let marker_at = first.find(MARKER)?;
    // Everything before the marker must be just a comment prefix and spaces,
    // otherwise this is a coincidence in somebody else's file.
    let lead = &first[..marker_at];
    if !lead
        .trim_end()
        .chars()
        .all(|c| c == '#' || c == ';' || c.is_whitespace())
    {
        return None;
    }

    let hash: String = first[marker_at + MARKER.len()..]
        .trim()
        .chars()
        .take_while(|c| c.is_ascii_hexdigit())
        .collect();
    if hash.len() != 64 {
        return None;
    }

    // The notice line is part of the header, not the body.
    let body = match rest.split_once('\n') {
        Some((notice, after)) if notice.contains(NOTICE) => after,
        _ => rest,
    };
    Some((hash, body))
}

/// Classify what is currently at `path`.
pub fn inspect(path: &Path) -> FileState {
    let contents = match std::fs::read_to_string(path) {
        Ok(c) => c,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return FileState::Absent,
        Err(e) => {
            return FileState::Unreadable {
                reason: e.to_string(),
            };
        }
    };

    let Some((claimed, body)) = split_header(&contents) else {
        return FileState::Foreign;
    };

    let actual = body_hash(body);
    if actual == claimed {
        FileState::Managed { hash: actual }
    } else {
        FileState::Drifted {
            expected: claimed,
            actual,
        }
    }
}

/// Read the body of a managed file, for diffing against a fresh render.
pub fn read_body(path: &Path) -> Result<Option<String>> {
    match std::fs::read_to_string(path) {
        Ok(contents) => Ok(split_header(&contents).map(|(_, body)| body.to_string())),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(ConfigError::Io {
            path: path.to_path_buf(),
            source: e,
        }),
    }
}

/// Write `contents` to `path` atomically.
///
/// The temporary file is created in the same directory so the rename is a true
/// atomic replace — a temp file in `/tmp` would be a copy across filesystems and
/// could leave a half-written config behind.
pub fn write_atomic(path: &Path, contents: &str, mode: u32) -> Result<()> {
    use std::io::Write;
    use std::os::unix::fs::PermissionsExt;

    let dir = path.parent().ok_or_else(|| ConfigError::BadPath {
        path: path.to_path_buf(),
        reason: "has no parent directory".into(),
    })?;
    std::fs::create_dir_all(dir).map_err(|e| ConfigError::Io {
        path: dir.to_path_buf(),
        source: e,
    })?;

    let file_name = path.file_name().ok_or_else(|| ConfigError::BadPath {
        path: path.to_path_buf(),
        reason: "has no file name".into(),
    })?;
    let mut temp = dir.join(file_name);
    temp.as_mut_os_string().push(".unihelm-tmp");

    {
        let mut file = std::fs::File::create(&temp).map_err(|e| ConfigError::Io {
            path: temp.clone(),
            source: e,
        })?;
        file.write_all(contents.as_bytes())
            .map_err(|e| ConfigError::Io {
                path: temp.clone(),
                source: e,
            })?;
        file.set_permissions(std::fs::Permissions::from_mode(mode))
            .map_err(|e| ConfigError::Io {
                path: temp.clone(),
                source: e,
            })?;
        // Durable before the rename: a power cut between write and rename should
        // leave the old config, not an empty new one.
        file.sync_all().map_err(|e| ConfigError::Io {
            path: temp.clone(),
            source: e,
        })?;
    }

    std::fs::rename(&temp, path).map_err(|e| {
        let _ = std::fs::remove_file(&temp);
        ConfigError::Io {
            path: path.to_path_buf(),
            source: e,
        }
    })?;

    // Also sync the directory, so the rename itself survives a crash.
    if let Ok(dir_handle) = std::fs::File::open(dir) {
        let _ = dir_handle.sync_all();
    }
    Ok(())
}

/// Remove a managed file, refusing to delete one we did not write.
pub fn remove_managed(path: &Path) -> Result<bool> {
    match inspect(path) {
        FileState::Absent => Ok(false),
        FileState::Foreign => Err(ConfigError::Foreign {
            path: path.to_path_buf(),
        }),
        FileState::Unreadable { reason } => Err(ConfigError::BadPath {
            path: path.to_path_buf(),
            reason,
        }),
        FileState::Managed { .. } | FileState::Drifted { .. } => {
            std::fs::remove_file(path).map_err(|e| ConfigError::Io {
                path: path.to_path_buf(),
                source: e,
            })?;
            Ok(true)
        }
    }
}

/// A unified-ish diff, for the "somebody edited this" screen.
///
/// Not a real diff algorithm: line-by-line is enough to show a sysadmin what
/// they changed, and pulling in a diff crate for one screen is weight the
/// budget does not need.
pub fn simple_diff(current: &str, proposed: &str) -> Vec<DiffLine> {
    let current: Vec<&str> = current.lines().collect();
    let proposed: Vec<&str> = proposed.lines().collect();
    let mut out = Vec::new();

    let mut i = 0;
    while i < current.len() || i < proposed.len() {
        match (current.get(i), proposed.get(i)) {
            (Some(a), Some(b)) if a == b => out.push(DiffLine {
                line: i + 1,
                kind: DiffKind::Same,
                text: (*a).to_string(),
            }),
            (Some(a), Some(b)) => {
                out.push(DiffLine {
                    line: i + 1,
                    kind: DiffKind::Removed,
                    text: (*a).to_string(),
                });
                out.push(DiffLine {
                    line: i + 1,
                    kind: DiffKind::Added,
                    text: (*b).to_string(),
                });
            }
            (Some(a), None) => out.push(DiffLine {
                line: i + 1,
                kind: DiffKind::Removed,
                text: (*a).to_string(),
            }),
            (None, Some(b)) => out.push(DiffLine {
                line: i + 1,
                kind: DiffKind::Added,
                text: (*b).to_string(),
            }),
            (None, None) => break,
        }
        i += 1;
    }
    out
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct DiffLine {
    pub line: usize,
    pub kind: DiffKind,
    pub text: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum DiffKind {
    Same,
    Added,
    Removed,
}

/// A file the panel owns, and where it lives.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ManagedFile {
    pub path: PathBuf,
    pub mode: u32,
    pub comment_style: CommentStyle,
}

impl ManagedFile {
    /// An nginx include, 0644 so nginx (running as its own user) can read it.
    pub fn nginx(path: impl Into<PathBuf>) -> Self {
        Self {
            path: path.into(),
            mode: 0o644,
            comment_style: CommentStyle::Hash,
        }
    }

    /// A PHP-FPM pool file. Comments are semicolons, and it is read by the FPM
    /// master, which runs as root.
    pub fn fpm_pool(path: impl Into<PathBuf>) -> Self {
        Self {
            path: path.into(),
            mode: 0o644,
            comment_style: CommentStyle::Semicolon,
        }
    }

    /// A MariaDB drop-in. Read by `mariadbd` as root before it drops to the
    /// `mysql` user, and hash-commented like the rest of the my.cnf family.
    pub fn mysql(path: impl Into<PathBuf>) -> Self {
        Self {
            path: path.into(),
            mode: 0o644,
            comment_style: CommentStyle::Hash,
        }
    }

    pub fn state(&self) -> FileState {
        inspect(&self.path)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_freshly_written_file_reads_back_as_managed() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("site.conf");
        let body = "server {\n    listen 443 ssl;\n}\n";

        write_atomic(&path, &with_header(body, CommentStyle::Hash), 0o644).unwrap();

        match inspect(&path) {
            FileState::Managed { hash } => assert_eq!(hash, body_hash(body)),
            other => panic!("expected Managed, got {other:?}"),
        }
        assert_eq!(read_body(&path).unwrap().as_deref(), Some(body));
    }

    #[test]
    fn a_human_edit_is_detected_rather_than_overwritten() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("site.conf");
        write_atomic(
            &path,
            &with_header("server {\n}\n", CommentStyle::Hash),
            0o644,
        )
        .unwrap();

        // Somebody adds a line by hand and does not touch the header.
        let contents = std::fs::read_to_string(&path).unwrap();
        std::fs::write(&path, format!("{contents}# added by a sysadmin at 3am\n")).unwrap();

        let state = inspect(&path);
        assert!(state.is_drifted(), "expected drift, got {state:?}");
        assert!(
            !state.is_safe_to_overwrite(),
            "a drifted file must never be silently replaced"
        );
    }

    #[test]
    fn a_file_we_never_wrote_is_foreign_not_ours() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("site.conf");
        std::fs::write(&path, "server {\n    # hand-written years ago\n}\n").unwrap();

        assert_eq!(inspect(&path), FileState::Foreign);
        assert!(!inspect(&path).is_safe_to_overwrite());
        assert!(matches!(
            remove_managed(&path),
            Err(ConfigError::Foreign { .. })
        ));
        assert!(
            path.exists(),
            "a foreign file must survive a failed removal"
        );
    }

    #[test]
    fn a_forged_header_does_not_make_a_foreign_file_ours() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("site.conf");
        // The marker appears, but inside a directive rather than as a comment.
        std::fs::write(
            &path,
            "server_name UNIHELM-MANAGED sha256:0000;\nserver {}\n",
        )
        .unwrap();
        assert_eq!(inspect(&path), FileState::Foreign);
    }

    #[test]
    fn a_truncated_or_bogus_hash_is_not_trusted() {
        let dir = tempfile::tempdir().unwrap();
        for (name, header) in [
            ("short.conf", "# UNIHELM-MANAGED sha256:abc\n"),
            ("empty.conf", "# UNIHELM-MANAGED sha256:\n"),
            ("nonhex.conf", "# UNIHELM-MANAGED sha256:zzzz\n"),
        ] {
            let path = dir.path().join(name);
            std::fs::write(&path, format!("{header}server {{}}\n")).unwrap();
            assert_eq!(inspect(&path), FileState::Foreign, "{name}");
        }
    }

    #[test]
    fn semicolon_comment_style_works_for_fpm_pools() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("pool.conf");
        let body = "[site]\nuser = uh_abc\n";
        write_atomic(&path, &with_header(body, CommentStyle::Semicolon), 0o644).unwrap();

        let raw = std::fs::read_to_string(&path).unwrap();
        assert!(raw.starts_with("; UNIHELM-MANAGED"), "got: {raw}");
        assert!(matches!(inspect(&path), FileState::Managed { .. }));
        assert_eq!(read_body(&path).unwrap().as_deref(), Some(body));
    }

    #[test]
    fn atomic_write_leaves_no_temporary_files_behind() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("site.conf");
        write_atomic(&path, "hello\n", 0o644).unwrap();
        write_atomic(&path, "hello again\n", 0o644).unwrap();

        let leftovers: Vec<_> = std::fs::read_dir(dir.path())
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .filter(|n| n.contains("unihelm-tmp"))
            .collect();
        assert!(leftovers.is_empty(), "left behind: {leftovers:?}");
    }

    #[test]
    fn atomic_write_sets_the_requested_mode() {
        use std::os::unix::fs::PermissionsExt;
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("secret.conf");
        write_atomic(&path, "key\n", 0o600).unwrap();
        let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode, 0o600);
    }

    #[test]
    fn removing_a_managed_file_reports_whether_it_was_there() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("site.conf");
        assert!(
            !remove_managed(&path).unwrap(),
            "absent means nothing was removed"
        );

        write_atomic(&path, &with_header("x\n", CommentStyle::Hash), 0o644).unwrap();
        assert!(remove_managed(&path).unwrap());
        assert!(!path.exists());
    }

    #[test]
    fn a_drifted_file_can_still_be_removed_deliberately() {
        // Deleting a site should not be blocked by an edit to its vhost — the
        // user asked for the site to go away.
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("site.conf");
        write_atomic(&path, &with_header("x\n", CommentStyle::Hash), 0o644).unwrap();
        std::fs::write(
            &path,
            std::fs::read_to_string(&path).unwrap() + "# edited\n",
        )
        .unwrap();
        assert!(inspect(&path).is_drifted());
        assert!(remove_managed(&path).unwrap());
    }

    #[test]
    fn the_header_hash_covers_the_body_only() {
        // Re-rendering identical content must produce an identical file, or
        // every render would look like a change.
        let a = with_header("server {}\n", CommentStyle::Hash);
        let b = with_header("server {}\n", CommentStyle::Hash);
        assert_eq!(a, b);
        assert_ne!(a, with_header("server { }\n", CommentStyle::Hash));
    }

    #[test]
    fn diff_shows_what_changed() {
        let diff = simple_diff("a\nb\nc\n", "a\nB\nc\nd\n");
        let added: Vec<_> = diff
            .iter()
            .filter(|d| d.kind == DiffKind::Added)
            .map(|d| &d.text)
            .collect();
        let removed: Vec<_> = diff
            .iter()
            .filter(|d| d.kind == DiffKind::Removed)
            .map(|d| &d.text)
            .collect();
        assert_eq!(added, vec!["B", "d"]);
        assert_eq!(removed, vec!["b"]);
    }
}
